name: example
publish_to: none

environment:
  sdk: ">=3.5.2 <4.0.0"
  flutter: ">=3.24.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_shaders:
    path: ../
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  shaders:
    - shaders/inkwell.frag
    - shaders/sampler.frag
    - shaders/solid_color.frag
    - shaders/blank.frag
    - packages/flutter_shaders/shaders/pixelation.frag
