name: flutter_shaders
description: A collection of utilities for working with the FragmentProgram API in Flutter.
repository: https://github.com/jonahwilliams/flutter_shaders
issue_tracker: https://github.com/jonahwilliams/flutter_shaders/issues
version: 0.1.4

environment:
  sdk: ">=3.5.2 <4.0.0"
  flutter: ">=3.24.2"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
